name: InfernoChristmas
version: '1.0.0'
main: dev.demondev.infernoChristmas.InfernoChristmas
api-version: '1.21'
load: STARTUP
authors: [ DemonDev ]
description: Christmas Plugin for infernorifts
commands:
  present:
    description: present command
  advent:
    description: Opens the Advent Calendar GUI
    usage: /advent
    permission: adventcalendar.open
    aliases: [calendar]
  adventsimulate:
    description: Simulates a specific day for testing
    usage: /adventsimulate <day>
    permission: adventcalendar.simulate
  permissions:
    adventcalendar.open:
      default: true
    adventcalendar.simulate:
      default: op
